Sis_Atualizacoes/Controllers/ProjetosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sis_Atualizacoes.Models;
using Sis_Atualizacoes.ViewModels;

namespace Sis_Atualizacoes.Controllers
{
    public class ProjetosController : Controller
    {
        private readonly Sis_AtualizacoesContext _context;

        public ProjetosController(Sis_AtualizacoesContext context)
        {
            _context = context;
        }

        // GET: Projetos
        public async Task<IActionResult> Index()
        {
              return _context.Projetos != null ? 
                          View(await _context.Projetos.ToListAsync()) :
                          Problem("Entity set 'Sis_AtualizacoesContext.Projetos'  is null.");
        }

        // GET: Projetos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Projetos == null)
            {
                return NotFound();
            }

            var projeto = await _context.Projetos.FirstOrDefaultAsync(p => p.IdProjeto == id);
            if (projeto == null)
            {
                return NotFound();
            }

            var pacotes = await _context.PacotesAtualizacoes
                            .Where(p => p.IdProj == id) 
                            .ToListAsync();

            if (pacotes == null)
            {
                return NotFound();
            }

            var projetoListViewModel = new ProjetoListViewModel
            {
                Projeto = projeto,
                Pacote = pacotes
            };

            return View(projetoListViewModel);
        }

        // GET: Projetos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projetos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProjeto,NomProjeto")] Projetos projetos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projetos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(projetos);
        }

        // GET: Projetos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Projetos == null)
            {
                return NotFound();
            }

            var projetos = await _context.Projetos.FindAsync(id);
            if (projetos == null)
            {
                return NotFound();
            }
            return View(projetos);
        }

        // POST: Projetos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProjeto,NomProjeto")] Projetos projetos)
        {
            if (id != projetos.IdProjeto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projetos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjetosExists(projetos.IdProjeto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(projetos);
        }

        // GET: Projetos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Projetos == null)
            {
                return NotFound();
            }

            var projetos = await _context.Projetos
                .FirstOrDefaultAsync(m => m.IdProjeto == id);
            if (projetos == null)
            {
                return NotFound();
            }

            return View(projetos);
        }

        // POST: Projetos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Projetos == null)
            {
                return Problem("Entity set 'Sis_AtualizacoesContext.Projetos'  is null.");
            }
            var projetos = await _context.Projetos.FindAsync(id);
            if (projetos != null)
            {
                _context.Projetos.Remove(projetos);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjetosExists(int id)
        {
          return (_context.Projetos?.Any(e => e.IdProjeto == id)).GetValueOrDefault();
        }
    }
}

Sis_Atualizacoes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sis_Atualizacoes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/estiloPrincipal.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/cards.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/projetoDetails.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sis_Atualizacoes.styles.css" asp-append-version="true" />
</head>
<body>
    <section class="navbar-expand-lg p-0 mr-0">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="sidebar col-xl-3 fixed-top  py-3 responsividade" id="fixo" style="margin-top: 10%;">
                        <ul class="navbar-nav flex-column ajuste-ul-sidebar" id="rolavel">
                            <li class="nav-item ">
                                <a class="nav-link text-white sidebar-link caixa__alta" asp-controller="Projetos" asp-action="Details" asp-route-id="1">Argus</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white sidebar-link caixa__alta">Simba</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white sidebar-link caixa__alta">Sittel</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white sidebar-link caixa__alta">PAI</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link text-white sidebar-link caixa__alta">Passaport</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <nav class="bg-dark fixed-top  main-content">
        <ul class="d-flex bd-highlight mb-0 ajuste-ul-nav">
            <!--<i class="fa-solid fa-bars fa-xl text-white mt-4 menu-toggler" ></i>-->
            <li style="padding-right: 15px; padding-left: 10px; margin-top: 0; padding-bottom: 10px; margin-top: 10px;">
                <div class="menu-icon ">
                    <div>
                        <input type="checkbox" id="check">
                        <label for="check">
                            <i class="fas fa-bars fa-2x text-white menu-toggler" style="margin-top: 15px;"></i>
                        </label>
                    </div>
            </li>
            <li class="nav-ajuste-cepadsi" style="padding-right: 13%; padding-bottom: 20px;">
                <h1 class=" text-white d-block mx-auto text-center pl-2 mb-2  caixa__alta" style="padding-bottom: 9.3%;  margin-top: 6%;">SisAt</h1>
            </li>
            <li class=" mr-auto p-3 bd-highlight text-white nav-ajuste intranet-none" style="margin-left: 1%;">
                </i><h6><strong>SPAI - sistema de atualizações </strong>| Mantenha todas aplicaçoes atualizadas</h6>
            </li>

            <li class="p-2  text-white pr-4 nav-ajuste ml-5">

                <i class="fa-sharp fa-solid fa-building-columns pr-1"></i>
                <a class="text-white caixa__alta" style="text-decoration: none;" href=""></a>
            </li>
            <li class="p-2 bd-highlight text-white pr-5 nav-ajuste">
                <i class="fa-solid fa-magnifying-glass"></i>
                <a class="text-white caixa__alta" style="text-decoration: none;" href=""></a>
            </li>
        </ul>
    </nav>


    <div class="container main-content-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Sis_Atualizacoes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const checkbox = document.getElementById("check");
            const sidebar = document.getElementById("fixo");
            const mainContent = document.getElementById("main-content");

            const sidebarWidth = 417;

            checkbox.addEventListener("change", function () {
                if (checkbox.checked) {
                    sidebar.style.transform = `translateX(-${sidebarWidth}px)`;
                    mainContent.style.width = "100%";
                    mainContent.style.marginLeft = "0";
                } else {
                    sidebar.style.transform = "translateX(0)";
                    // mainContent.style.width = `calc(100% - ${sidebarWidth}px)`;
                    mainContent.style.marginLeft = `${sidebarWidth}px`;
                }
            });
        });


    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>